# Generated by Django 2.1.5 on 2019-01-24 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Construction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(choices=[('LEFT', 0), ('CENTER', 1), ('RIGHT', 2)], default=0, help_text='카드의 위치')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='카드의 순서')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.ConstructionClass')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='갱신 시간')),
                ('title', models.CharField(help_text='세션 이름', max_length=32)),
                ('current', models.PositiveSmallIntegerField(default=0, help_text='현재 턴')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='construction',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='session.Session'),
        ),
    ]
