# Generated by Django 2.1.5 on 2019-01-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='construction',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[('PREPARE', 0), ('LEFT', 1), ('CENTER', 2), ('RIGHT', 3)], default=0, help_text='카드의 위치'),
        ),
    ]
