# Generated by Django 2.1.5 on 2019-01-24 03:53

from django.db import migrations, models
import django.db.models.deletion
import functools
import game.tools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(game.tools.combine_file_path, *(), **{}))),
                ('count', models.PositiveSmallIntegerField(default=0, help_text='게임에 포함된 매수')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EffectClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to=functools.partial(game.tools.combine_file_path, *(), **{}))),
                ('title', models.CharField(help_text='효과명', max_length=32, unique=True)),
                ('desc', models.TextField(blank=True, help_text='설명', null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NumberClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.PositiveSmallIntegerField(default=0, help_text='숫자')),
            ],
        ),
        migrations.AddField(
            model_name='constructionclass',
            name='effect',
            field=models.ForeignKey(help_text='카드 효과', on_delete=django.db.models.deletion.CASCADE, to='game.EffectClass'),
        ),
        migrations.AddField(
            model_name='constructionclass',
            name='number',
            field=models.ForeignKey(help_text='카드 숫자', on_delete=django.db.models.deletion.CASCADE, to='game.NumberClass'),
        ),
    ]
