# Generated by Django 2.1.5 on 2019-02-08 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20190208_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructionclass',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='ConstructionClass'),
        ),
        migrations.AlterField(
            model_name='effectclass',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='EffectClass'),
        ),
    ]
