# Generated by Django 2.1.7 on 2019-02-18 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20190210_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionclass',
            name='image',
        ),
        migrations.RemoveField(
            model_name='effectclass',
            name='image',
        ),
    ]
